version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin123
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 30s
      retries: 3

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: fastapi_service
    ports:
      - "8000:8000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672/
    volumes:
      - ./api:/app

  processor:
    build:
      context: ./processor
      dockerfile: Dockerfile
    container_name: processor_service
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      - RABBITMQ_URL=amqp://admin:admin123@rabbitmq:5672/
    volumes:
      - ./processor:/app